theme:
  name: readthedocs
  
site_name: CsoundQt 1.1.3 Documentation

nav:
  - Home: 'index.md'
  - 'Getting Started':
    - Installation: 'gs_install.md'
    - First Run and Trouble Shooting: 'gs_firstrun.md'
    - Edit and Get Help: 'gs_edit.md'
    - Run or Render To File: 'gs_run.md'
    - Widgets: 'gs_widgets.md'
    - Examples: 'gs_examples.md'
    - Contribute: 'gs_contribute.md'
  - Configuration:
    - Introduction: 'config_intro.md'
    - Run Tab: 'config_run.md'
    - Advanced Tab: 'config_advanced.md'
    - General Tab: 'config_general.md'
    - Editor Tab: 'config_editor.md'
    - Widgets Tab: 'config_widgets.md'
    - Environment Tab: 'config_environment.md'
    - External Tab: 'config_external.md'
    - Template Tab: 'config_template.md'
  - Menus: 
    - CsoundQt Menu Items: 'menu.md'
  - Additional Features:
    - Utilities: 'utilities.md'
    - HTML5 Support: 'html5.md'
    - PythonQt: 'pythonqt.md'
  - Tips and Tricks: 
    - Tips and Tricks: 'tips.md'

